name: My custom workflow manual migration for project-5

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
        ports:
          - 9200:9200
          - 9300:9300
        options: --name elasticsearch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2