name: gha-result

on:
  pull_request:
    branches:
      - branch-1
  push:
    branches:
      - branch-1

jobs:
  build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          jdk:
            - name: Oracle JDK 11
              version: '17'
      steps:
        - name: Checkout code
          uses: actions/checkout@v3.5.0

        - uses: actions/setup-java@v3.12.0
          with:
            java-version: ${{ matrix.java.version }}
          run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true

