name: gha-result

on:
  pull_request:
    branches:
      - branch-1
  push:
    branches:
      - branch-1

jobs:
  build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          jdk:
            - name: Oracle JDK 17
              version: '17'

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setting up java version
          uses: actions/setup-java@v4
          with:
            java-version: ${{ matrix.jdk.version }}
            distribution: 'adopt'

        - run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true
        - run: sudo rm -rf /var/lib/elasticsearch