name: My custom workflow manual migration for project-5

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
        ports:
          - 9200:9200
          - 9300:9300
        options: --name elasticsearch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setting up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          architecture: 'x64'
          distribution: 'adopt'