name: My custom workflow manual migration for project-5

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
        ports:
          - 9200:9200
          - 9300:9300
        options: --name elasticsearch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setting up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          architecture: 'x64'
          distribution: 'adopt'

      - name: clearing Elasticsearch present data
        run: sudo rm -rf /var/lib/elasticsearch

      - name: Elasticsearch Instalation-1
        run: |
          curl -L -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.11.3-amd64.deb
          sudo dpkg -i --force-confnew elasticsearch-8.11.3-amd64.deb
          sudo cp ./src/test/resources/elasticsearch.yml /etc/elasticsearch/elasticsearch.yml
          sudo cat /etc/elasticsearch/elasticsearch.yml
          sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
          sudo service elasticsearch start
          sleep 30